/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialProfielenRouteImport } from './routes/social-profielen'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as NieuwsRouteImport } from './routes/nieuws'
import { Route as MerkprofielRouteImport } from './routes/merkprofiel'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as FotoBibliotheekRouteImport } from './routes/foto-bibliotheek'
import { Route as ContentStudioRouteImport } from './routes/content-studio'
import { Route as CampagnesRouteImport } from './routes/campagnes'
import { Route as BoekRouteImport } from './routes/boek'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'

const SocialProfielenRoute = SocialProfielenRouteImport.update({
  id: '/social-profielen',
  path: '/social-profielen',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const NieuwsRoute = NieuwsRouteImport.update({
  id: '/nieuws',
  path: '/nieuws',
  getParentRoute: () => rootRouteImport,
} as any)
const MerkprofielRoute = MerkprofielRouteImport.update({
  id: '/merkprofiel',
  path: '/merkprofiel',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoBibliotheekRoute = FotoBibliotheekRouteImport.update({
  id: '/foto-bibliotheek',
  path: '/foto-bibliotheek',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentStudioRoute = ContentStudioRouteImport.update({
  id: '/content-studio',
  path: '/content-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesRoute = CampagnesRouteImport.update({
  id: '/campagnes',
  path: '/campagnes',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekRoute = BoekRouteImport.update({
  id: '/boek',
  path: '/boek',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/boek': typeof BoekRoute
  '/campagnes': typeof CampagnesRoute
  '/content-studio': typeof ContentStudioRoute
  '/foto-bibliotheek': typeof FotoBibliotheekRoute
  '/kalender': typeof KalenderRoute
  '/merkprofiel': typeof MerkprofielRoute
  '/nieuws': typeof NieuwsRoute
  '/planning': typeof PlanningRoute
  '/seo': typeof SeoRoute
  '/social-profielen': typeof SocialProfielenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/boek': typeof BoekRoute
  '/campagnes': typeof CampagnesRoute
  '/content-studio': typeof ContentStudioRoute
  '/foto-bibliotheek': typeof FotoBibliotheekRoute
  '/kalender': typeof KalenderRoute
  '/merkprofiel': typeof MerkprofielRoute
  '/nieuws': typeof NieuwsRoute
  '/planning': typeof PlanningRoute
  '/seo': typeof SeoRoute
  '/social-profielen': typeof SocialProfielenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/boek': typeof BoekRoute
  '/campagnes': typeof CampagnesRoute
  '/content-studio': typeof ContentStudioRoute
  '/foto-bibliotheek': typeof FotoBibliotheekRoute
  '/kalender': typeof KalenderRoute
  '/merkprofiel': typeof MerkprofielRoute
  '/nieuws': typeof NieuwsRoute
  '/planning': typeof PlanningRoute
  '/seo': typeof SeoRoute
  '/social-profielen': typeof SocialProfielenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/auth'
    | '/boek'
    | '/campagnes'
    | '/content-studio'
    | '/foto-bibliotheek'
    | '/kalender'
    | '/merkprofiel'
    | '/nieuws'
    | '/planning'
    | '/seo'
    | '/social-profielen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/auth'
    | '/boek'
    | '/campagnes'
    | '/content-studio'
    | '/foto-bibliotheek'
    | '/kalender'
    | '/merkprofiel'
    | '/nieuws'
    | '/planning'
    | '/seo'
    | '/social-profielen'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/auth'
    | '/boek'
    | '/campagnes'
    | '/content-studio'
    | '/foto-bibliotheek'
    | '/kalender'
    | '/merkprofiel'
    | '/nieuws'
    | '/planning'
    | '/seo'
    | '/social-profielen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  BoekRoute: typeof BoekRoute
  CampagnesRoute: typeof CampagnesRoute
  ContentStudioRoute: typeof ContentStudioRoute
  FotoBibliotheekRoute: typeof FotoBibliotheekRoute
  KalenderRoute: typeof KalenderRoute
  MerkprofielRoute: typeof MerkprofielRoute
  NieuwsRoute: typeof NieuwsRoute
  PlanningRoute: typeof PlanningRoute
  SeoRoute: typeof SeoRoute
  SocialProfielenRoute: typeof SocialProfielenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social-profielen': {
      id: '/social-profielen'
      path: '/social-profielen'
      fullPath: '/social-profielen'
      preLoaderRoute: typeof SocialProfielenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nieuws': {
      id: '/nieuws'
      path: '/nieuws'
      fullPath: '/nieuws'
      preLoaderRoute: typeof NieuwsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merkprofiel': {
      id: '/merkprofiel'
      path: '/merkprofiel'
      fullPath: '/merkprofiel'
      preLoaderRoute: typeof MerkprofielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto-bibliotheek': {
      id: '/foto-bibliotheek'
      path: '/foto-bibliotheek'
      fullPath: '/foto-bibliotheek'
      preLoaderRoute: typeof FotoBibliotheekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-studio': {
      id: '/content-studio'
      path: '/content-studio'
      fullPath: '/content-studio'
      preLoaderRoute: typeof ContentStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes': {
      id: '/campagnes'
      path: '/campagnes'
      fullPath: '/campagnes'
      preLoaderRoute: typeof CampagnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boek': {
      id: '/boek'
      path: '/boek'
      fullPath: '/boek'
      preLoaderRoute: typeof BoekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  BoekRoute: BoekRoute,
  CampagnesRoute: CampagnesRoute,
  ContentStudioRoute: ContentStudioRoute,
  FotoBibliotheekRoute: FotoBibliotheekRoute,
  KalenderRoute: KalenderRoute,
  MerkprofielRoute: MerkprofielRoute,
  NieuwsRoute: NieuwsRoute,
  PlanningRoute: PlanningRoute,
  SeoRoute: SeoRoute,
  SocialProfielenRoute: SocialProfielenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
